### ISSUE TITLE
Migration from eRowan to Rowan

### ISSUE THREAD

**Issue by zikarium** [Sifchain/peggy#108]

**Comment by zikarium** [comment]
Elliot says: "Please communicate with executives Jazear and Aidan to confirm token name and symbol as well as the case for each of these."

**Comment by zikarium** [comment]
Jazear defined that the name should be "Rowan" and the symbol should be "Rowan".

![Capturar.PNG](https://images.zenhubusercontent.com/60f729b7b9da54de9e274ec7/11ebee57-7a70-475e-a6ac-d2b7981e90aa)

**Comment by banshee** [comment]
We can create the new Rowan token any time; the migration needs to know the address.
