### ISSUE TITLE
Check adjustments to Aidan's PR

### ISSUE THREAD

**Issue by zikarium** [Sifchain/peggy#118]
PR: https://github.com/Sifchain/sifnode/pull/1881

**Comment by zikarium** [comment]
Made the adjustments and asked for a review from Elliot.
LGMT.

**Comment by pandaring2you** [comment]
Issue moved to [Sifchain/sifnode #1904](https://github.com/Sifchain/sifnode/issues/1904) via [**ZenHub**](https://www.zenhub.com/)
