### ISSUE TITLE
Review Cosmos ADR on Coin Source Tracing

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#45]
Task from technical architecture meeting: 
Review https://docs.cosmos.network/master/architecture/adr-001-coin-source-tracing.html to determine if there are conflicts with the proposed naming convention (https://docs.google.com/document/d/1DFYQhiSEArzsDlDfL5GgTnjrAwpz7iS81nCkbhZYCX0/edit#heading=h.t97u3lczh8rk). Also check if it would make sense to integrate a similar coin tracing scheme into our proposed naming convention. 

Technical Architecture Meeting Notes: https://docs.google.com/document/d/1turfT2RQSwEN2cOmyL2ekLKlXZkSYxLoJmjmClm6Z70/edit# 

Estimating this to be a 3, please change if not.

**Comment by pandaring2you** [comment]
cc @ElliotFriedman

**Comment by pandaring2you** [comment]
Hey @timlind did you have any thoughts on this - if task is no longer relevant/you'll focused on .42 instead, feel free to close out.

**Comment by timlind** [comment]
I think the decision needed around naming was made. I'm going to leave it open for a bit longer though to see if any further work / research on IBC has any affect here.
