### ISSUE TITLE
Implement Dynamic Gas Fees in UI

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#46]
Problem: ETH gas prices over the past month avg ~170 gwei. Our static fee has often ends up undercharging for unpeg transactions. 

Constraint: We'll be making significant changes to the peggy backend and don't want to introduce additional logic that will be difficult to change later.  

Solution: Make gas price dynamic based on a multiple of avg gas price. We got final confirmation from Jazear via future of Peggy meeting on this fix. 

@ElliotFriedman - Can you provide precise specs on the gas price estimation?

**Comment by sifmoon** [comment]
@pandaring2you fyi here is the doc: https://docs.google.com/document/d/18ss6WlmrgqsmKmZhhlROXQre0hxCh9MwZ4HFuWZ2dYA/edit#heading=h.mxbpzfilf0c5

Can you extract what is being said in the doc into this ticket for @59023g ?

**Comment by sifmoon** [comment]
Closing this ticket for ticket #230.
