### ISSUE TITLE
Discussion Item: What work will be required to remove token decimal normalization logic from CLP module?

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#47]
This came out of the future of peggy meeting on 3-23. 

Instead of normalizing token decimals in the CLP logic, the proposal is to normalize token decimals to 18 as soon as they are pegged into Sifchain. This is so that we do not have to pass decimal metadata in the token identifier. 

@AustinoBombino / (what's Tanmay's handle?) - What steps would need to be taken to remove the logic from the CLP module?

**Comment by AustinoBombino** [comment]
@Jedi2002

**Comment by AustinoBombino** [comment]
I think we can pull out the normalization code without too much of an issue. 

But switching to 18 across the board would require modifying clp state through an upgrade. We would have to change balances and recalculate pool units, which would definitely complicate things

**Comment by ElliotFriedman** [comment]
@AustinoBombino Let's consolidate this thread onto the future of peggy google doc so that we don't have multiple conversations in different locations around the same topic.

**Comment by pandaring2you** [comment]
no longer necessary. peggy 2.0 will import tokens without normalization logic, so the normalization logic in the clp should remain as is.
