### ISSUE TITLE
Discussion Item: How can we remove "c" prefix from all pegged tokens.

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#48]
This came out of the future of peggy meeting on 3-23.

We'd like to remove the c prefix from all tokens on Sifchain. cETH -> ETH . @AustinoBombino / @Tanmay - What steps would need to be taken to do this?

**Comment by 59023g** [comment]
Why? That's confusing from a user's standpoint. Ethereum "ETH" is not same as Sifchain "ETH." Prefix is a necessary distinction. If anything, change it to "s" to denote Sifchain.

**Comment by AustinoBombino** [comment]
cc @Jedi2002 

I agree that it would be confusing from a UX perspective to remove the prefix altogether.

That said, we would need to right an upgrade handler to modify state for pool, liquidity provider, and account objects.

**Comment by sifmoon** [comment]
@pandaring2you was the reason for this change this?
- We will treat ALL external tokens (no matter where they come from) by their token symbol. So, for example: ETH from BSC and Ethereum would both be under the same 'ETH' token distinction. 
- Was there more reasoning behind wnating to go this route? Just curious as to if we have points to the 'why we want to do this'.

**Comment by pandaring2you** [comment]
sorry for the delay on this. Jazear has a larger plan to aggregate equivalent wrapped tokens into the same pool. he's still working on the details. he sees this as an industry wide problem that we can eventually solve. will follow up when i get more details from him.

**Comment by sifmoon** [comment]
@pandaring2you i think what you are referring to is pointed out here: http://sifchain.aha.io/ahoy/messages/NvUL2IyCdn8Yr4iCf2gxiKcy3CUCyHoM/click?signature=15ef0074f174c5baa657fc1c086ddab5ccafce78&url=https%3A%2F%2Fsifchain.aha.io%2Ffeatures%2FSC-35%3Futm_source%3Dnotification_mailer%26utm_medium%3Demail%26utm_campaign%3Ddigest_email

**Comment by pandaring2you** [comment]
change already made on the frontend, will eventually switch to peggy 2.0 denom for the backend
