### ISSUE TITLE
Create Gas Oracle

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#52]
Create a gas prediction oracle for relayers. The purpose of the oracle is to give relayers a more accurate assessment of gas costs and thereby charge dynamic fees for unpegging EVM chains. @ElliotFriedman to provide specs

**Comment by pandaring2you** [comment]
Will work on spec with Elliot after Ceth task

**Comment by juniuszhou** [comment]
reference document as https://docs.google.com/document/d/1Wh_RaCEJGHxsG0fCxyife4ExEul5cDP3GlDC7Tlp-zU/edit

**Comment by phips28** [comment]
Will this enable dynamic fees in the frontend? currentlty its 220$ to unpeg. Pretty insane high 🙈
Is there an ETA on merging this?
Can I help?

**Comment by jkbrooks** [comment]
@phips28 you might be able to help as we'd prefer to get the open source dev community to take this on.  Look out for a request for help and instructions to engage in an upcoming Medium article

**Comment by pandaring2you** [comment]
DO NOT DO
