### ISSUE TITLE
Sifnode Relayer Whitelist Spec

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#58]
Sifnode will need to change how it accepts relayers signing off on prophecy claims. Instead of allowing this based on the whitelist and the users bonded power, we need to move to a structure where each chain has a relayer set of x users. X of the Y relayers will need to sign off on a prophecy to make it valid. Data structures will look something like this: 
networkbyte → list of relayers

This way, a separate set of relayers that need to sign off on prophecies for each network. The whitelist will move from: 
address → boolean
to
networkbyte → address → bool
This will require that when a relayer is started, it is passed a network byte that it should be looking at to see if the account that is running in that relayer is valid for the given network. This sanity check will stop relayers from listening to chains they are not authorized to broadcast transactions on.

**Comment by pandaring2you** [comment]
@ElliotFriedman to write up initial draft

**Comment by juniuszhou** [comment]
https://docs.google.com/document/d/1PgbYqT7KkVsDs66OciClbxVgFKT9JR4zVWpN1pBttCM/edit

**Comment by pandaring2you** [comment]
@ElliotFriedman - Did you get a chance to review the spec? Would be good to solidify implementation details as it's scheduled for next sprint.
