### ISSUE TITLE
Implement Standardize Token Identifiers

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#61]
EVM Based Chains ERC20
For all pegged ERC20 assets, their respective token names on sifchain will be comprised of the following three elements: ERC20 token address, chain id. A pegged ERC20 asset with token address 0xbF45BFc92ebD305d4C0baf8395c4299bdFCE9EA2, a chain ID of 1 and 18 decimals will have the following symbol on sifchain: 
coin/0xbF45BFc92ebD305d4C0baf8395c4299bdFCE9EA2/01
ibc/0xbF45BFc92ebD305d4C0baf8395c4299bdFCE9EA2

The coin is necessary at the start of the symbol because the regex in the cosmos module will not recognize it as a valid string unless it starts with a lowercase alphanumeric character.

EVM Based Chain Native Currency
For all pegged native chain currency, the token address in the symbol will be the address 0. This symbol will follow the naming convention of ERC20 tokens with the token address being address 0. For example, ethereum pegged in from the ethereum mainnet will be represented as the following:
coin/0x0000000000000000000000000000000000000000/01
ibc/0x0000000000000000000000000000000000000000/58

Rowan Naming
	Because rowan is a sifchain native asset, it shouldn’t behave like other currencies whose names will be defined by the smart contract address from the chain they are pegged in from. Rowan’s decimals are 18 and this is already implied so there should not be code changes necessary for this.

Nonconforming ERC20s
If the token has decimal specification -> convert to 18 decimals 
If the token has no decimal specification -> ???

**Comment by banshee** [comment]
Added some change suggestions

**Comment by pandaring2you** [comment]
Docs:

Coin Metadata: https://docs.google.com/document/d/1DFYQhiSEArzsDlDfL5GgTnjrAwpz7iS81nCkbhZYCX0/edit?ts=6054dc12#

Double Pegged Token Identifiers: https://docs.google.com/document/d/1A_N7I7c3NCJNntTPup0YPR3arX7a9wxQyfJ3svi-pIs/edit#

**Comment by pandaring2you** [comment]
Reorganizing Peggy 2.0 tasks. This will be broken up into multiple tasks as defined in Aha: https://sifchain.aha.io/bookmarks/epic_gantt_roadmaps/6956651921392517459?nav=Releases&product_id=SC
