### ISSUE TITLE
Bug Fixes to ebrelayer/ethBridge Cosmos .42 upgrade

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/peggy#80]
https://github.com/Sifchain/sifnode/pull/1132

**Comment by marshsif** [comment]
Jordan is there any specific scope to this ticket?

**Comment by pandaring2you** [comment]
no particular scope. this was meant to track work on resolving the ebrelayer bugs. based on today's meeting, estimate looks to be about 1 additional week of work.

**Comment by marshsif** [comment]
Ivan mentioned that one command was commented out/stubbed because he wasn't sure how to do in .42

Ivan didn’t remove functionality or change functionality from before
He noted that he ran ebrelayer to ensure it runs, and ran afunction to ensure it performed
