### ISSUE TITLE
Adjustments to Token Stats Page

### ISSUE THREAD

**Issue by sifmoon** [Sifchain/peggy#95]
**Problem Statement**: When viewing the token stats page in our DEX, it becomes time-consuming to manually scroll through to see which tokens a user is most interested in. For heavy traders, this time commitment is a sunk cost that could end up costing them valuable money in not being able to act on a trade quick enough. We need to make this table more user-friendly.

**One Liner:** Make the tokens stats page easier and quicker to use and navigate by introducing the ability to search, sort, and easily show the user's existing pools in a special section of the stats.

**Goals:** 
- Provide the ability for a user to search by a token symbol and be taken to that specific token's stats (thinking this could be a type-ahead and then jump the user to that spot while highlighting that row to bring attention to it? We could also do a type-ahead and filter out all other tokens to show ONLY the tokens that are meeting that search criteria? I kind of like the 2nd option better).
- Provide the ability for a user to easily sort by all columns in the token stats page. The user should be able to click ascending or descending on any column and the table to react to that sort desire.
-- We will have a lot more tokens here in the future so we may need to move to an 'info' page here instead? 
- Provide an area within the token stats page that brings attention to the user's tokens that they currently have liquidity in. This sort of acts like a 'my favorites' type indicator so users can easily see and sort by that indicator. For this, I am thinking we just add another column called 'My Pooled Tokens' with an some sort of indicator to represent those tokens a user has Liquidity in. This column should be sortable as well so users can bring their pooled tokens to the top of the list if desired.
-- This can either be a sort, OR could be section within info.sifchain that shows a users 'My Pools'.

**Non Goals:**
- To provide the ability for a user to 'favorite' specific tokens to bring them to the top o the list.
- To provide the ability for us to remember how a user likes their Token Stats filtered and to default to that.

**Expected Metrics Changes:**
- Decreased time to find a token in stats page.

**Comment by sifmoon** [comment]
@j-kappa we need designs for this as well! Let's chat through this too. We should really revamp this page a bit.

**Comment by bksifchain** [comment]
will be redone as part of FEv3
